### ISSUE TITLE
Convert columns with location to geometry type in database

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#3]
Columns:
. Location.Location
. FeatureOfInterest.Feature

**Comment by bertt** [comment]
Fixed

**Comment by Alystrasz** [comment]
Is the `Feature` type correctly implemented ?

Trying to store some additional data on Locations entities, the GeoJSON RFC specifies to create the entity as a `Feature` as follows :
```
{
      "name": "location name",
      "description": "description name",
      "encodingType": "application/vnd.geo+json",
      "location": {
            "type": "Feature",
            "geometry": {
                  "type": "Point",
                  "coordinates": [ -114.06, 42.05 ]
            },
            "properties": {
                  "receptionTime": "",
                  "randomStuff": [ 42, 43, 44 ]
            }
      }
}
```
... which does not work, since the server rejects it (`500 : pq: invalid GeoJson representation`).
Surprisingly, creating a Location as GeoJSON `Point` with additional properties is accepted by the server, while it shouldn't :

```
{
      "name": "location name",
      "description": "description name",
      "encodingType": "application/vnd.geo+json",
      "location": {
            "type": "Point",
            "coordinates": [-114.06, 42.05],
            "properties": {
                  "receptionTime": "",
                  "randomStuff": [42, 43, 44]
            }
      }
}
```

**Comment by bertt** [comment]
at the moment only the geometry part of GeoJSON is accepted. We're working on a fix to accept the complete GeoJSON (also for Observation.FeatureOfInterest and Datastream.ObservedArea).

**Comment by Alystrasz** [comment]
Hello @bertt, 
Here I am 2 years later, with the exact same issue :)
Have you implemented the afore-mentioned fix?
