### ISSUE TITLE
Fix drone.io and unit tests

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#79]
. drone.io is deprecated
. coveralls is not working
. some unit tests are failing (mainly querybuilder.go and observation.go)

**Comment by tebben** [comment]
Drone.io has no free hosting anymore, going to move to Travis CI

**Comment by tebben** [comment]
- Added GOST repo @ Travis CI
  - Created .travis.yml config file 
  - Updated build badge
  - Removed GOST from coveralls and added it again to cleanup because of wrong build numbers after moving to Travis CI

**ToDo**
  - Trigger docker build for latest tag after passing build (currently also triggered fro docker cloud when build failed)
